name: Auto Deploy Blog

on:
  workflow_dispatch:
  push:
    branches:
      - master
      
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 12.7.0
      
      - name: Set environment variables
        run: |
          echo "const token = '${{ secrets.REPO_TOKEN }}';export default token;" > utils/index.js

      - name: npm install
        run: npm install

      - name: Build
        run: npm run build

      - uses: actions/upload-pages-artifact@v1
        with:
            path: docs/.vuepress/dist

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v2
